### ISSUE TITLE
Can u please offer a specific.h5 file or provide a script to generate the.h5 file in this experiment ?Thank you!

### ISSUE THREAD

**Issue by dominCodebug** [gvtulder/cross-view-transformers#1]
Hello, I am a first-year graduate student from China. I have just started to learn the knowledge related to multi-modal about medical images. I think your work is very good, with clear thinking and excellent performance. It is an excellent work, so I want to run the code to further understand the details of the experiment. But because of the limited capacity and lack of a.h5 file, although I generated my own.h5 file, failed to run this code. So, could you please provide a specific.h5 file, or provide a script to generate the.h5 file in this experiment? This is my email address 1776863572@qq.com . I’m sorry if I disturbed you. Looking forward to your reply!
<img width="416" alt="image" src="https://user-images.githubusercontent.com/31788909/142756120-b82f1b2a-170a-48ca-a355-6dbe1eadc2a1.png">

**Comment by shawnyuen** [comment]
Can you provide me with specific .h5 files, or scripts to generate these .h5 files?
My e-mail address is 403568338@qq.com, thank you so much!

**Comment by gvtulder** [comment]
Thanks for the interest. The scripts to preprocess the files are now available in the `data-scripts-*` directories. Unfortunately, I can't share the HDF5 files on GitHub, because they are derived from the original CBIS-DDSM and CheXpert data. You can download those from their respective sources.
